api_platform:
  title: Système de réservation de vols d'avion # titre de la documentation de l’API
  version: 1.0.0
  formats:
    json: ["application/json"] # format par défaut de retour des ressources API
    jsonld: ["application/ld+json"] #format optionnel pour les tests
  patch_formats:
    json: ["application/merge-patch+json", "application/json"]
  defaults:
    stateless: true
    cache_headers:
      vary: ["Content-Type", "Authorization", "Origin"]
  swagger: # activer l'authentification JWT depuis Swagger (permettre les actions sur les verbes HTTPs en ayant le bon token JWT)
    api_keys:
      JWT:
        name: Authorization
        type: header
