twig:
  file_name_pattern: "*.twig"
  paths:
    "emails/templates": "emails" # déclaration du namespace des emails
    "%kernel.project_dir%/public/css": css #Ajout du chemin vers le dossier "public/css"

when@test:
  twig:
    strict_variables: true
